server:
  port: 8081
  servlet:
    context-path: /

websocket_server:
  port: 7070

session:
  id: "${sessionId}"

websocket:
  link: "${WEB_SOCKET_URL:localhost:9001}"

spring:
  application:
    name: Server

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
  show-actuator: false

logging:
  level:
    root: info
    eu.chargetime.ocpp.jsonclientimplementation: debug
    jdbc: off
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    jdbc.resultsettable: info
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off
